environment:
  matrix:
  - nodejs_version: "0.12"
  - nodejs_version: 4
  - nodejs_version: 5

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm test

build: off